export const EVT_CRAFT_MODAL_OPEN = 'EVT_CRAFT_MODAL_OPEN'
export const EVT_SET_CRAFT = 'EVT_SET_CRAFT';
export const EVT_ADD_CRAFT = 'EVT_ADD_CRAFT';

export const EVT_COMPONENT_MODAL_OPEN = 'EVT_COMPONENT_MODAL_OPEN'
export const EVT_SET_COMPONENT = 'EVT_SET_COMPONENT';

export const EVT_TALENT_MODAL_OPEN = 'EVT_TALENT_MODAL_OPEN'
export const EVT_FILL_SHIP_POOLS = 'EVT_FILL_SHIP_POOLS'
