export const EVT_COMPONENT_MODAL_OPEN = 'EVT_COMPONENT_MODAL_OPEN'
export const EVT_TALENT_MODAL_OPEN = 'EVT_TALENT_MODAL_OPEN'
export const EVT_FILL_SHIP_POOLS = 'EVT_FILL_SHIP_POOLS'
export const EVT_SET_COMPONENT = 'EVT_SET_COMPONENT';
